version: '3.3'
services:
    db:
        image: postgres:latest
        environment:
            - POSTGRES_DB=bioApp
            - POSTGRES_USER=BIOAPP
            - POSTGRES_PASSWORD=B104PP
        ports:
            - "5432:5432"
        volumes:
            - "./postgres_data:/var/lib/postgresql/data"
    
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=bioApp@mail.com
            - PGADMIN_DEFAULT_PASSWORD=B104PP
        ports:
            - 5050:80
